apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: minikube-start
build:
  artifacts:
  - image: frontend
    context: frontend
    docker:
      dockerfile: frontend/Dockerfile
  - image: migration
    context: migration
    docker:
      dockerfile: migration/Dockerfile
  - image: server
    context: server
    docker:
      dockerfile: server/Dockerfile
  - image: server-integration-test
    context: server/integration-test
    docker:
      dockerfile: server/integration-test/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: postgres
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        wait: true
        setValueTemplates:
          auth:
            username: "user"
            password: "password"
            database: "db"
      - name: migration
        chartPath: charts/migration
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_migration}}"
          image.tag: "{{.IMAGE_TAG_migration}}"
          env:
            username: "user"
            password: "password"
            database: "db"
          appendTime: true
      - name: server
        chartPath: charts/server
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_server}}"
          image.tag: "{{.IMAGE_TAG_server}}"
          test.image.repository: "{{.IMAGE_REPO_server_integration_test}}"
          test.image.tag: "{{.IMAGE_TAG_server_integration_test}}"
          env:
            username: "user"
            password: "password"
            database: "db"
      - name: frontend
        chartPath: charts/frontend
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_frontend}}"
          image.tag: "{{.IMAGE_TAG_frontend}}"