apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: minikube-start
build:
  artifacts:
  - image: frontend
    context: frontend
    docker:
      dockerfile: frontend/Dockerfile
  - image: server
    context: server
    docker:
      dockerfile: server/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: postgres
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
      - name: frontend
        chartPath: charts/frontend
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_frontend}}"
          image.tag: "{{.IMAGE_TAG_frontend}}"
      - name: server
        chartPath: charts/server
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_server}}"
          image.tag: "{{.IMAGE_TAG_server}}"